# Generated by Django 3.2.9 on 2021-11-17 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='box',
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='size',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='размер бокса'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='срок аренды'),
        ),
        migrations.DeleteModel(
            name='StorageBox',
        ),
    ]
