# Generated by Django 3.2.9 on 2021-11-18 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 месяц'), (2, '2 месяца'), (3, '3 месяца'), (4, '4 месяца'), (5, '5 месяцев'), (6, '6 месяцев'), (7, '7 месяцев'), (8, '8 месяцев'), (9, '9 месяцев'), (10, '10 месяцев'), (11, '11 месяцев'), (12, '1 год')], default=1, verbose_name='срок хранения'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='size',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='размер бокса в м² (каждый следующий м² + 150 ₽ в мес.)'),
        ),
    ]
