# Generated by Django 3.2.9 on 2021-11-19 09:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('storage_rental', '0002_auto_20211118_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='storingorder',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='storingorder',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='storingorder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='обработан'),
        ),
        migrations.AddField(
            model_name='order',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rental_orders', to='storage_rental.storage', verbose_name='склад'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='общая стоимость аренды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person_name',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='size',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='размер бокса в м²'),
        ),
    ]
