# Generated by Django 3.2.9 on 2021-11-19 11:27

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('storage_rental', '0003_auto_20211119_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='passport_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.MinValueValidator(6)], verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person_name',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, validators=[django.core.validators.MinValueValidator(10)], verbose_name='номер телефона'),
        ),
    ]
