# Generated by Django 3.2.9 on 2021-11-19 14:41

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('storage_rental', '0004_auto_20211119_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('SKIS', 'Лыжи'), ('SNOWBOARD', 'Сноуборд'), ('BIKE', 'Велосипед'), ('TIRES', 'Шины')], db_index=True, default='SKIS', max_length=9, verbose_name='тип инвентаря'),
        ),
        migrations.AlterField(
            model_name='order',
            name='passport_number',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person_name',
            field=models.CharField(db_index=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='название'),
        ),
    ]
