# Generated by Django 3.2.9 on 2021-11-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_rental', '0007_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoСode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=15, verbose_name='код')),
                ('start_date', models.DateField(verbose_name='начальная дата действия')),
                ('end_date', models.DateField(verbose_name='конечная дата действия')),
                ('discount', models.PositiveIntegerField(verbose_name='скидка')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
            },
        ),
    ]
